### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by jimpriest** [bartdag/pylinkvalidator#3] opened 2015-08-11 13:26 UTC
Making progress on CSV export but while testing plain text output I ran into this issue while scanning our site:

    error (<type 'exceptions.UnicodeEncodeError'>): 'ascii' codec can't encode 
    character u'\u2019' in position 58: ordinal not in range(128): 
    http://my.private.url/about/press-releases/joe-smith-named-sunshine’s-officer

I can do: 'print u'\u2019' - and it correctly prints the single quote in my terminal?  

Digging through the code I found in crawler.py where it appears to be handling the exception  but I'm not sure how to fix (new to Python)

    # Something bad happened when opening the url
    exception = ExceptionStr(
    unicode(type(response.exception)),
    unicode(response.exception))

**Comment by jimpriest** [comment] 2015-08-11 13:36
I wonder if this is a Python version issue...  using the same URL for testing:

* Server: Python 2.7.5 - error
* Workstation: Python 2.7.10 - no error

**Comment by bartdag** [comment] 2015-08-11 13:44
Hi,

you mean that the URL contains a unicode character?

**Comment by jimpriest** [comment] 2015-08-11 15:08
Yes - the link I'm checking has a single quote in it.   It does seem to be Python related - I've setup the same link both with the single quote and encoded and it works fine.

Thanks for the help!

**Comment by bartdag** [comment] 2015-08-11 15:38
All right, I'll try to see if I can detect this and work around the problem by url-encoding the url before passing it to the url lib. Interesting corner case :-)

**Comment by jimpriest** [comment] 2015-08-11 16:42
Thanks for the help!

**Comment by jimpriest** [comment] 2015-08-11 19:34
Another case: error (<type 'exceptions.UnicodeEncodeError'>): 'ascii' codec can't encode character u'\u2014' in position 62: ordinal not in range(128): 

And I don't know what I was doing before but it IS happening on both my workstation and server (different Python 2.x) versions.

**Comment by bartdag** [comment] 2015-08-12 00:31
Do you have some reproducible test case. I tried crawling urls with utf-8 characters and could not reproduce :-(

**Comment by bartdag** [comment] 2015-08-12 13:25
So I could finally reproduce the error. I created a branch, nonasciiiris, which contains a fix. I'll have to write a test and clean the code a little, but this works for me on Python 2.7 and 3.4. If you have a chance to test it, I would be interested in knowing if it worked for you.

If you look at the commit, you'll see a lot of encode/decode to make sure that we treat one byte at a time and support both Python 2 and Python 3..

**Comment by jimpriest** [comment] 2015-08-12 14:23
Sure - will test this morning...  I was hacking on this myself...

I found:
http://stackoverflow.com/questions/492483/setting-the-correct-encoding-when-piping-stdout-in-python

And added:

reload(sys)
sys.setdefaultencoding('utf-8')

To crawler.py and the error went away.  I don't think that's the
correct solution though, just a hack. :)

Will checkout your branch and let you know!


Thanks,

Jim

**Comment by bartdag** [comment] 2015-08-12 14:28
That's another error actually that can indeed happen if you run the code in a terminal that does not handle utf-8 by default. The original error is that urlopen does not accept non-ascii characters (see the comment here: https://hg.python.org/cpython/file/3.4/Lib/http/client.py#l1013)

**Comment by jimpriest** [comment] 2015-08-12 15:46
Testing nonasciiiris branch: 

    SUCCESS Crawled 224 urls in 39.98 seconds
 
No encoding errors reported.

I'm runing another test with depth = 2 but seems like this is fixed.

**Comment by jimpriest** [comment] 2015-08-12 16:53
Same command run against same site using my fork with the 

   reload(sys)
   sys.setdefaultencoding('utf-8')

hack returns no encoding errors...

**Comment by bartdag** [comment] 2015-08-12 17:33
Hi Jim, could you send me by email the command you are running just to make sure there isn't something obvious I am missing.

Also, is this happening with Python 2.7.10 and which OS are you using?

The default encoding hack will help stdin and stdout, but it's clearly not something we can ship with pylinkvalidator :-D 

Thanks for your help in figuring out what the problem is!

**Comment by jimpriest** [comment] 2015-08-12 17:47
Yeah I may have posted negative results too soon - I'm getting inconsistent
results... still testing...

python pylinkvalidate.py --progress http://myurl/ --depth=1 --workers=10
--format=plain --output=jim2.txt --parser=lxml

Python version: 2.7.10
OS: Fedora 22

Have lots of encoding pages bookmarked :) Seems like a common issue in
Python 2.x.

Jim

**Comment by jimpriest** [comment] 2015-08-12 18:59
OK - using the new branch, I ran a longer test with depth=2, and see NO encoding errors:
ERROR Crawled 19751 urls with 299 error(s) in 3610.23 seconds

**Comment by bartdag** [comment] 2015-08-12 20:21
Thanks for testing!

Just to make sure, do the non encoding-related errors make sense (404, or timeout or 500)?

**Comment by jimpriest** [comment] 2015-08-12 20:33
So far I'm really only looking at 404s and haven't found any false positives for those yet.  Everything looks good other than the encoding errors.

**Comment by bartdag** [comment] 2015-08-13 16:17
Interestingly I found two other potential sources of errors:

if you use --progress or output the results in the console and your system is not set with a utf-8 encoding, you'll get an error when pylinkvalidator prints a url with non-ascii characters. Cleaning the URL like the nonasciiiris branch is doing is a good solution for this.

also, if beautifulsoup/chardet cannot determine the right encoding of the page, the decoding will either raise an exception or the wrong link will be detected which will result in a false 404. I have a fix for this one coming too.

**Comment by jimpriest** [comment] 2015-08-13 16:31
Interesting - I'm always using --progress - but I believe my terminal is setup correctly for UTF-8.

Today I'm doing some benchmarks between the various modes/parser options trying to determine which one is fastest.

**Comment by bartdag** [comment] 2015-08-17 01:05
I just merged the fix in @master. I also added an option to prefer the encoding specified by the server instead of trying to detect the encoding.

I believe using the server's encoding will be a bit faster but if the encoding of the source does not match the server's encoding (e.g., server says the encoding is utf-8, but the source is encoded in latin-1), there may be errors in the URLs if they are not already properly quoted/escaped.

**Comment by jimpriest** [comment] 2015-08-17 13:13
Cool!  Thanks for all the fixes.

How does this work with pip? I originally installed via pip.  Does it link
to Github somehow?

Jim

**Comment by bartdag** [comment] 2015-08-17 14:00
Nope, I still need to build a release. If you can confirm that the issue is fixed on @master on your side, I'll make a release tomorrow morning.

**Comment by jimpriest** [comment] 2015-08-17 15:43
Hmm.  Updated my master and tryed out the new server encodng flag and get an error?

    python pylinkvalidate.py --progress --depth=1 --workers=10 --output=jim.txt --mode=thread 
    --parser=lxml --prefer-server-encoding http://my.url.com/
    
    Usage: pylinkvalidate.py [options] URL ...
    pylinkvalidate.py: error: no such option: --prefer-server-encoding

**Comment by bartdag** [comment] 2015-08-17 16:17
Thanks for trying to validate. I don't think you have the latest version of the code or perhaps your PYTHONPATH is pointing to another directory?

**Comment by jimpriest** [comment] 2015-08-17 16:51
Grrr... pythonpath was it.

**Closed** 2015-08-18 08:43 UTC
Labels: bug
